name: Integration Tests

env:
  SCRIPT_NAMES: |
    omnichain_swap
    omnichain_staking
    omnichain_multioutput
    messaging_counter
    messaging_message
    messaging_value
    messaging_warriors

on:
  workflow_dispatch:
    inputs:
      scriptName:
        type: choice
        description: "Script to run"
        options: ${{ env.SCRIPT_NAMES }}
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  integration_tests:
    name: Run integration tests in sequence
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run scripts in sequence
        run: |
          for script in ${{ env.SCRIPT_NAMES }}
          do
            ./scripts/$script.sh
          done
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
