name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      scriptName:
        type: choice
        description: "Script to run"
        options:
          - omnichain_swap
          - omnichain_staking
          - omnichain_multioutput
          - messaging_counter
          - messaging_message
          - messaging_value
          - messaging_warriors
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  integration_tests:
    name: Run ${{ matrix.scriptName || github.event.inputs.scriptName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scriptName:
          - omnichain_swap
          - omnichain_staking
          - omnichain_multioutput
          - messaging_counter
          - messaging_message
          - messaging_value
          - messaging_warriors
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Test Script
        run:
          ./scripts/${{ matrix.scriptName || github.event.inputs.scriptName}}.sh
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
